# Use NodeJS base image
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies by copying
# package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install && npm install typescript -g

# Copy app source
COPY . .

RUN tsc

# Bind the port that the image will run on
EXPOSE 3000

# Define the Docker image's behavior at runtime
CMD ["node", "dist/index.js"]
